baseURL = "https://julianstanley.com/"
languageCode = "en-us"
title = "Julian Stanley"
theme = "pulp"
googleAnalytics = "UA-109124750-1"
canonifyurls = true
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Julian Stanley"
    description = "Computational Biologist"
    githubUsername = "julianstanley"
    accent = "white"
    showBorder = false
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "Monokai Sublime"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "R"]
    copyright = "Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal). Thanks for visiting! [{Website Source}](https://github.com/julianstanley/julianstanley.com)"

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    
[[menu.main]]
    url = "/about/about"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "https://scholar.google.com/citations?user=N0D7hFYAAAAJ&hl=en"
    name = "Google Scholar"
    weight = 4
    target = "_blank"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:stanley.ju@husky.neu.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/julianstanley/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/julianstanley_/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/julianstanley/"
    name = "linkedin"
    weight = 4
    
[[menu.icon]]
    url="https://scholar.google.com/citations?user=N0D7hFYAAAAJ&hl=en"
    name = "google-scholar"
    weight = 5

